In [1]:
import vcf
import numpy as np
import pandas as pd
from collections import Counter

##### creating a dataframe out of chromosome, positions , ref and alt alleles

In [2]:
vcf_sample1_snp = vcf.Reader(open("sample1_final_filtered_snps.vcf","r"))
vcf_sample2_snp = vcf.Reader(open("sample2_final_filtered_snps.vcf","r"))
vcf_sample3_snp = vcf.Reader(open("sample3_final_filtered_snps.vcf","r"))
vcf_sample4_snp = vcf.Reader(open("sample4_final_filtered_snps.vcf","r"))
vcf_sample5_snp = vcf.Reader(open("sample5_final_filtered_snps.vcf","r"))
vcf_sample6_snp = vcf.Reader(open("sample6_final_filtered_snps.vcf","r"))
vcf_sample7_snp = vcf.Reader(open("sample7_final_filtered_snps.vcf","r"))

In [3]:
lis_vcfs=[vcf_sample1_snp, vcf_sample2_snp, vcf_sample3_snp, vcf_sample4_snp, vcf_sample5_snp,
          vcf_sample6_snp, vcf_sample7_snp]

In [4]:
n = len(lis_vcfs)
count=0
res_list=[]
df=pd.DataFrame()
for vcff in lis_vcfs:
    count+=1
    dictionary={}
    sample=[]
    for record in vcff:
        sample.append([record.CHROM, record.POS, record.REF,' '.join([str(elem) for elem in (record.ALT)])])
    dictionary[count] = sample
    for val in dictionary.values():
        df[count] = pd.Series(val)
        for elements in val:
            res_list.append(elements)

In [5]:
df

,1,2,3,4,5,6,7
0,"[chr1, 1734970, C, T]","[chr1, 1734970, C, T]","[chr1, 3999637, C, G]","[chr1, 1032184, A, G]","[chr1, 754503, G, A]","[chr1, 3722742, T, C]","[chr1, 1501064, T, G]"
1,"[chr1, 4158540, C, T]","[chr1, 1762698, T, C]","[chr1, 4002498, T, C]","[chr1, 3240199, G, A]","[chr1, 3738640, A, C]","[chr1, 4475911, G, T]","[chr1, 2019706, G, C]"
2,"[chr1, 4891603, A, G]","[chr1, 1779036, T, C]","[chr1, 4002766, A, G]","[chr1, 3242061, C, T]","[chr1, 3740473, A, G]","[chr1, 4952655, C, A]","[chr1, 4035673, A, G]"
3,"[chr1, 4908656, G, A]","[chr1, 1788689, C, G]","[chr1, 4120796, A, C]","[chr1, 4508569, A, G]","[chr1, 3744249, A, G]","[chr1, 4961864, G, A]","[chr1, 4292038, C, T]"
4,"[chr1, 4908901, A, G]","[chr1, 2015441, C, T]","[chr1, 4120987, C, T]","[chr1, 4522798, C, T]","[chr1, 3745133, A, G]","[chr1, 5037892, C, G]","[chr1, 4292080, C, T]"
5,"[chr1, 4909808, T, C]","[chr1, 4481081, C, T]","[chr1, 4150527, G, A]","[chr1, 4526751, C, T]","[chr1, 3745193, T, C]","[chr1, 5037893, G, C]","[chr1, 4295551, C, T]"
6,"[chr1, 4913873, T, C]","[chr1, 4549380, G, A]","[chr1, 4180839, G, A]","[chr1, 4549235, G, T]","[chr1, 3747603, T, C]","[chr1, 5044082, T, A]","[chr1, 4301354, A, G]"
7,"[chr1, 4913940, C, T]","[chr1, 4549402, A, G]","[chr1, 4249460, T, C]","[chr1, 4597082, G, C]","[chr1, 3748605, G, A]","[chr1, 5044089, C, G]","[chr1, 4333076, A, T]"
8,"[chr1, 4913966, A, G]","[chr1, 4555701, T, A]","[chr1, 4497118, C, T]","[chr1, 4597089, G, A]","[chr1, 3756493, T, C]","[chr1, 5044116, T, C]","[chr1, 4541390, A, C]"
9,"[chr1, 4916204, G, T]","[chr1, 4555847, C, T]","[chr1, 4497130, G, A]","[chr1, 4597600, A, G]","[chr1, 3769590, G, C]","[chr1, 5044137, G, T]","[chr1, 4541425, T, C]"
10,"[chr1, 4917460, C, T]","[chr1, 4557403, T, C]","[chr1, 4569547, A, G]","[chr1, 4597855, T, C]","[chr1, 4300806, C, T]","[chr1, 5044138, G, A]","[chr1, 4548453, A, G]"
11,"[chr1, 4917545, A, G]","[chr1, 4926174, A, G]","[chr1, 4601301, A, C]","[chr1, 4597866, A, T]","[chr1, 4640902, T, C]","[chr1, 5045030, G, A]","[chr1, 4549330, G, A]"
12,"[chr1, 4918109, G, A]","[chr1, 4955862, C, T]","[chr1, 4601322, G, T]","[chr1, 4598001, G, C]","[chr1, 4647158, G, C]","[chr1, 5046230, C, T]","[chr1, 4552482, C, A]"
13,"[chr1, 4918649, G, A]","[chr1, 4995146, G, A]","[chr1, 4601558, G, T]","[chr1, 4598021, T, C]","[chr1, 4647175, C, T]","[chr1, 5047010, C, T]","[chr1, 4632828, C, A]"
14,"[chr1, 4918806, T, C]","[chr1, 4995168, A, C]","[chr1, 4601585, G, A]","[chr1, 4598027, C, A]","[chr1, 4874426, A, T]","[chr1, 5047038, A, G]","[chr1, 4961987, A, T]"
15,"[chr1, 4919012, T, C]","[chr1, 4995175, T, C]","[chr1, 4646073, C, A]","[chr1, 4598090, G, A]","[chr1, 4874427, A, T]","[chr1, 5048624, T, C]","[chr1, 5338372, T, C]"
16,"[chr1, 4919240, G, A]","[chr1, 5003504, G, A]","[chr1, 4765955, T, C]","[chr1, 4598217, A, G]","[chr1, 4885655, C, G]","[chr1, 5048934, A, C]","[chr1, 5914292, A, G]"
17,"[chr1, 4919488, G, A]","[chr1, 5037892, C, G]","[chr1, 4843918, C, T]","[chr1, 4598424, G, A]","[chr1, 4888012, G, T]","[chr1, 5073658, A, C]","[chr1, 5931205, A, G]"
18,"[chr1, 4919762, C, G]","[chr1, 5037893, G, C]","[chr1, 5045786, G, C]","[chr1, 4598454, T, C]","[chr1, 4907703, T, C]","[chr1, 5081066, T, C]","[chr1, 6784464, C, T]"
19,"[chr1, 4919795, G, A]","[chr1, 5045030, G, A]","[chr1, 5045794, T, C]","[chr1, 4600321, C, T]","[chr1, 5077202, G, T]","[chr1, 5081173, G, A]","[chr1, 6785946, G, T]"
20,"[chr1, 4920200, T, C]","[chr1, 5045786, G, C]","[chr1, 5161874, C, T]","[chr1, 4600491, T, G]","[chr1, 5078939, T, C]","[chr1, 5085217, T, C]","[chr1, 6785947, C, T]"
21,"[chr1, 4922255, G, A]","[chr1, 5045794, T, C]","[chr1, 5283721, G, A]","[chr1, 4600621, C, G]","[chr1, 5220054, T, C]","[chr1, 5093686, T, C]","[chr1, 6963402, C, G]"
22,"[chr1, 4923098, A, G]","[chr1, 5048624, T, C]","[chr1, 5353708, C, A]","[chr1, 4600746, C, T]","[chr1, 5222388, C, T]","[chr1, 5214585, C, T]","[chr1, 6963417, G, A]"
23,"[chr1, 4923189, A, G]","[chr1, 5048934, A, C]","[chr1, 5642511, G, A]","[chr1, 4600784, G, T]","[chr1, 5222596, C, T]","[chr1, 5218365, T, C]","[chr1, 7088750, T, C]"
24,"[chr1, 4923277, A, G]","[chr1, 5053263, T, C]","[chr1, 6185532, G, A]","[chr1, 4602088, A, T]","[chr1, 5651994, G, T]","[chr1, 5222728, A, G]","[chr1, 7158561, T, C]"
25,"[chr1, 4923347, C, T]","[chr1, 5055604, T, C]","[chr1, 6597861, T, C]","[chr1, 4603127, C, T]","[chr1, 6373698, T, C]","[chr1, 5282551, T, C]","[chr1, 7160542, T, C]"
26,"[chr1, 4923387, C, T]","[chr1, 5068210, A, G]","[chr1, 6907322, T, A]","[chr1, 4603324, T, A]","[chr1, 6869365, A, G]","[chr1, 5284844, G, A]","[chr1, 7185514, G, C]"
27,"[chr1, 4923474, G, T]","[chr1, 5068245, A, G]","[chr1, 7219665, A, G]","[chr1, 4603363, C, T]","[chr1, 6870942, T, C]","[chr1, 5285070, T, C]","[chr1, 7186325, G, A]"
28,"[chr1, 4924395, G, A]","[chr1, 5085949, C, T]","[chr1, 7220284, G, A]","[chr1, 4603370, T, G]","[chr1, 7093899, C, T]","[chr1, 5709728, C, T]","[chr1, 7191171, G, A]"
29,"[chr1, 4924822, G, A]","[chr1, 5085955, A, G]","[chr1, 7224189, T, C]","[chr1, 4606273, T, C]","[chr1, 7110577, A, G]","[chr1, 5731017, G, A]","[chr1, 7196659, C, T]"
...,...,...,...,...,...,...,...
81215,"[chrUn_gl000234, 37119, C, T]","[chr19, 43702342, C, T]",NaN,NaN,NaN,NaN,NaN
81216,"[chrUn_gl000234, 38428, T, G]","[chr19, 44193244, A, C]",NaN,NaN,NaN,NaN,NaN
81217,"[chrUn_gl000234, 40115, T, A]","[chr19, 44193729, C, T]",NaN,NaN,NaN,NaN,NaN
81218,"[chrUn_gl000234, 40145, A, G]","[chr19, 44194781, C, T]",NaN,NaN,NaN,NaN,NaN
81219,"[chrUn_gl000234, 40151, C, T]","[chr19, 44559853, C, T]",NaN,NaN,NaN,NaN,NaN
81220,"[chrUn_gl000234, 40162, T, C]","[chr19, 44564981, G, A]",NaN,NaN,NaN,NaN,NaN
81221,"[chrUn_gl000234, 40208, T, C]","[chr19, 44565125, A, G]",NaN,NaN,NaN,NaN,NaN
81222,"[chrUn_gl000234, 40212, G, A]","[chr19, 44565427, A, G]",NaN,NaN,NaN,NaN,NaN
81223,"[chr17_gl000203_random, 35687, A, T]","[chr19, 44570847, A, C]",NaN,NaN,NaN,NaN,NaN
81224,"[chr17_gl000203_random, 35700, G, A]","[chr19, 44572048, C, G]",NaN,NaN,NaN,NaN,NaN
81225,"[chrUn_gl000231, 7130, A, G]","[chr19, 44573415, G, A]",NaN,NaN,NaN,NaN,NaN
81226,"[chrUn_gl000231, 14540, A, G]","[chr19, 44575027, A, G]",NaN,NaN,NaN,NaN,NaN
81227,"[chrUn_gl000231, 25068, A, T]","[chr19, 44576302, C, T]",NaN,NaN,NaN,NaN,NaN
81228,"[chrM, 119, T, C]","[chr19, 44580758, T, C]",NaN,NaN,NaN,NaN,NaN
81229,"[chrM, 150, T, C]","[chr19, 44584556, C, T]",NaN,NaN,NaN,NaN,NaN
81230,"[chrM, 152, T, C]","[chr19, 44585159, T, A]",NaN,NaN,NaN,NaN,NaN
81231,"[chrM, 2354, C, T]","[chr19, 44586076, T, C]",NaN,NaN,NaN,NaN,NaN
81232,"[chrM, 2485, C, T]","[chr19, 44587930, T, C]",NaN,NaN,NaN,NaN,NaN
81233,"[chrM, 3506, A, G]","[chr19, 44588278, G, T]",NaN,NaN,NaN,NaN,NaN
81234,"[chrM, 5047, G, A]","[chr19, 44588325, G, T]",NaN,NaN,NaN,NaN,NaN
81235,"[chrM, 7865, C, T]","[chr19, 44588786, T, G]",NaN,NaN,NaN,NaN,NaN
81236,"[chrM, 8252, G, A]","[chr19, 44588789, C, T]",NaN,NaN,NaN,NaN,NaN
81237,"[chrM, 8702, G, A]","[chr19, 44588969, G, A]",NaN,NaN,NaN,NaN,NaN
81238,"[chrM, 12851, G, A]","[chr19, 44589016, A, G]",NaN,NaN,NaN,NaN,NaN
81239,"[chrM, 15933, C, T]","[chr19, 44589042, T, C]",NaN,NaN,NaN,NaN,NaN
81240,"[chrM, 16173, C, T]","[chr19, 44590558, C, T]",NaN,NaN,NaN,NaN,NaN
81241,"[chrM, 16185, C, A]","[chr19, 44591360, G, A]",NaN,NaN,NaN,NaN,NaN
81242,"[chrM, 16191, C, T]","[chr19, 44591554, G, C]",NaN,NaN,NaN,NaN,NaN
81243,"[chrM, 16195, C, T]","[chr19, 44592099, G, T]",NaN,NaN,NaN,NaN,NaN
81244,"[chrM, 16294, C, T]","[chr19, 44592100, C, T]",NaN,NaN,NaN,NaN,NaN

In [6]:
df[1].head()

0    [chr1, 1734970, C, T]
1    [chr1, 4158540, C, T]
2    [chr1, 4891603, A, G]
3    [chr1, 4908656, G, A]
4    [chr1, 4908901, A, G]
Name: 1, dtype: object

In [7]:
df[2].head()

0    [chr1, 1734970, C, T]
1    [chr1, 1762698, T, C]
2    [chr1, 1779036, T, C]
3    [chr1, 1788689, C, G]
4    [chr1, 2015441, C, T]
Name: 2, dtype: object

In [8]:
res_list[:10]

[['chr1', 1734970, 'C', 'T'],
 ['chr1', 4158540, 'C', 'T'],
 ['chr1', 4891603, 'A', 'G'],
 ['chr1', 4908656, 'G', 'A'],
 ['chr1', 4908901, 'A', 'G'],
 ['chr1', 4909808, 'T', 'C'],
 ['chr1', 4913873, 'T', 'C'],
 ['chr1', 4913940, 'C', 'T'],
 ['chr1', 4913966, 'A', 'G'],
 ['chr1', 4916204, 'G', 'T']]

In [9]:
n=len(lis_vcfs)       
counts=Counter(tuple(x) for x in res_list)
val=[]
for k in counts.keys():
    if counts[k] == n:
        val.append(k)
        
print("number of snps common in all ", n, " files is ", len(val), " and they are, \n", val)

number of snps common in all  7  files is  37  and they are,
 [('chr1', 121485071, 'C', 'A'), ('chr1', 121485088, 'T', 'A'), ('chr6', 58776745, 'C', 'T'), ('chr6', 58776782, 'A', 'T'), ('chr6', 58777109, 'C', 'T'), ('chr6', 58777178, 'G', 'T'), ('chr6', 58777366, 'A', 'G'), ('chr6', 58777419, 'T', 'C'), ('chr6', 58777546, 'G', 'A'), ('chr6', 58777573, 'C', 'T'), ('chr6', 58777836, 'A', 'C'), ('chr6', 58778019, 'T', 'G'), ('chr6', 58778025, 'A', 'G'), ('chr6', 58778039, 'G', 'C'), ('chr6', 58778081, 'T', 'G'), ('chr6', 58778082, 'T', 'C'), ('chr6', 58778108, 'G', 'C'), ('chr6', 58778207, 'G', 'A'), ('chr6', 58778244, 'A', 'T'), ('chr6', 58778404, 'C', 'A'), ('chr6', 58778405, 'C', 'T'), ('chr6', 58778412, 'T', 'C'), ('chr6', 58778452, 'A', 'C'), ('chr6', 58778482, 'G', 'A'), ('chr6', 58778584, 'T', 'G'), ('chr6', 58778788, 'T', 'C'), ('chr6', 58778922, 'C', 'A'), ('chr6', 58778967, 'T', 'C'), ('chr6', 58778989, 'T', 'C'), ('chr6', 58779007, 'C', 'T'), ('chr6', 58779308, 'T', 'C'), ('chr6', 58779328, 'A', 'G'), ('chr10', 42400642, 'C', 'A'), ('chr10', 42400643, 'A', 'G'), ('chr10', 42529432, 'T', 'A'), ('chrUn_gl000220', 140156, 'C', 'T'), ('chrUn_gl000220', 142271, 'G', 'C')]